development:
  sessions:
    default:
      database: 'dev'
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      hosts:
       - <%= URI(ENV['MONGOHQ_URL']).host + ':' + URI(ENV['MONGOHQ_URL']).port %>
      database: <%= URI(ENV['MONGOHQ_URL']).path.gsub(/^\//, '') %>
      username: 'heroku'
      password: 'deep sea creature'
