development:
  sessions:
    default:
      database: 'dev'
      hosts:
        - localhost:27017
production:
  sessions:
      default:
            database: 'app5975660'
            hosts:
             - alex.mongohq.com:10066
            username: admin
            password: 'deep sea creature'
