development:
  sessions:
    default:
      database: 'dev'
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: 'app5975660'
      username: 'heroku'
      password: 'deep sea creature'
      hosts:
       - alex.mongohq.com:10066
